language: node_js
services:
- mongodb
node_js:
- '0.10'
before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install mocha-lcov-reporter
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
  flowdock:
    secure: stXNeqjEKm4VQ/6s07y6zw7aIwzAWEqaPVos1+EkQeaWqsp9hpKImQUxgOFoWbTDQooX5RAuQy2JdqvymaKk/LuU9C6CTvwv7Am9u2EyAIhUlRd41LjoIAY32idRaNa5u3g8h3Mk6bh2EBir1E/DdikHMSoUxCzs6ER00BS6sao=
env:
  global:
    secure: DtwFuf9Lyr+WQstApt8n364Ga6DJFr2qMtyeY7oYYw+qCYrxEj8gv/lLTr053IkXO0ze5o5Pc++oNHsbOHwuIrQ9I/JueVpoJ7kr/8J4CL1ocDmFwJo3oXie0Uu9OdbINcr8blonsiBU0av5WUy3PdaKmLz0ZqSWPQM+g8OJt0w=
